In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,10,11) #between [0,10] give me 11 evenly spaced numbers

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(4,6)  #np.random.rand(4)

array([[0.21590159, 0.80914381, 0.45195039, 0.00287312, 0.5140123 ,
        0.21954579],
       [0.01200273, 0.22610798, 0.11764106, 0.17965659, 0.61276421,
        0.28520807],
       [0.62351526, 0.25548555, 0.61557499, 0.86763063, 0.26941224,
        0.62756458],
       [0.31071648, 0.86147283, 0.24938667, 0.58119062, 0.10474252,
        0.78197618]])

In [19]:
np.random.randn(6,2) #np.random.randn(4)

array([[ 0.04460608,  0.35710503],
       [ 0.47421666,  0.03055382],
       [-0.20629201, -0.8831818 ],
       [-0.26001997,  0.33273282],
       [-0.70557293,  0.02002038],
       [-0.88054263, -0.15764711]])

In [20]:
np.random.randint(100,800,(4,5))

array([[125, 582, 240, 541, 269],
       [627, 218, 208, 182, 135],
       [379, 264, 650, 632, 761],
       [783, 185, 709, 131, 146]])

In [21]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [22]:
arr = np.arange(0,25)

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranarr = np.random.randint(0,101,10)

In [25]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [26]:
ranarr.max()

99

In [27]:
ranarr.min()

2

In [28]:
ranarr.argmax() #index of max element in array

5

In [29]:
ranarr.argmin() #index of 

7

In [30]:
ranarr.dtype #attribute

dtype('int32')

In [31]:
arr.shape #attribute

(25,)

In [32]:
arr1 = np.arange(0,11)

In [33]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr[8]

8

In [35]:
arr[1:4]

array([1, 2, 3])

In [36]:
arr1[:5]

array([0, 1, 2, 3, 4])

In [37]:
arr1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr1[0:5] = 100

In [39]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [40]:
arr1 = np.arange(0,11)

In [41]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
slice_of_arr = arr1[0:5]

In [43]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [44]:
slice_of_arr[:] = 99

In [45]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [46]:
arr1    # observe.. any operation on slice_of_arr is affecting the original array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [47]:
arr_copy = arr1.copy()[:5]   # this will make sure we are making a copy of the original array

In [48]:
arr_copy

array([99, 99, 99, 99, 99])

In [49]:
arr_copy[:] = 60

In [50]:
arr_copy

array([60, 60, 60, 60, 60])

In [51]:
arr1

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [52]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [53]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
arr_2d.shape

(3, 3)

In [55]:
arr_2d[0]

array([ 5, 10, 15])

In [56]:
arr_2d[2]

array([35, 40, 45])

In [57]:
arr_2d[1,1]

25

In [58]:
arr_2d[0,2]

15

In [59]:
arr_2d[0,1:]

array([10, 15])

In [60]:
#conditional selection

arr2 = np.arange(0,10)

In [61]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr2 >2

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [63]:
bool_arr = arr2>4

In [64]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [65]:
arr2[bool_arr]

array([5, 6, 7, 8, 9])

In [66]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [67]:
dice_rolls

array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6,
       3, 6, 2, 3, 5, 6, 5])

In [68]:
np.count_nonzero(dice_rolls >2)

19

In [69]:
arr3 = np.arange(0,10)

In [70]:
arr3 + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [71]:
arr3 + arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
arr3 - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
arr3/arr3

<ipython-input-73-79a4ce7e4548>:1: RuntimeWarning: invalid value encountered in true_divide
  arr3/arr3


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [74]:
1/0 # but within numpy we will not get any error, we will get warning

ZeroDivisionError: division by zero

In [78]:
1/arr3

<ipython-input-78-e1e26bd1773d>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr3


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [79]:
np.sqrt(arr3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [80]:
np.sin(arr3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [81]:
np.log(arr3)

<ipython-input-81-472c3670d2f5>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr3)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [82]:
arr3.sum()

45

In [83]:
arr3.mean()

4.5

In [84]:
arr.var()

52.0

In [85]:
arr.std()

7.211102550927978

In [86]:
arr4 = np.arange(0,25).reshape(5,5)

In [87]:
arr4.sum()

300

In [89]:
arr4.sum(axis=0) # axis 0 represent sum around columns

array([50, 55, 60, 65, 70])

In [91]:
arr4.sum(axis=1)

array([ 10,  35,  60,  85, 110])